import type { DocumentMeta } from "./model.js";

/** File name of the generated corpus index, fixed by the documentation convention. */
export const INDEX_FILE = "INDEX.md";

export const MAX_SUMMARY_CHARS = 140;

/** The subset of document metadata the index line needs. */
export type IndexEntry = Pick<DocumentMeta, "path" | "title" | "summary" | "type" | "status">;

const INDEX_TITLE = "# Documentation index";
const GENERATED_NOTICE =
  '<!-- Generated by "compendio index-md"; manual edits are overwritten. -->';

/** Collapses whitespace and truncates, so each document stays on one short line. */
export function condenseSummary(text: string, maxChars: number = MAX_SUMMARY_CHARS): string {
  const collapsed = text.replace(/\s+/g, " ").trim();
  return collapsed.length <= maxChars ? collapsed : `${collapsed.slice(0, maxChars - 1)}…`;
}

/** Summary shown on a document line; falls back to the title when the
 * document has no intro paragraph after the H1. */
export function displaySummary(doc: { summary: string; title: string }): string {
  return condenseSummary(doc.summary.trim().length > 0 ? doc.summary : doc.title);
}

/**
 * One document per line — the format shared by INDEX.md and docs_overview.
 * Omits the `[type]` bracket segment and the `(status)` parenthesized segment
 * entirely when the corresponding field is absent (never `[undefined]` or an
 * empty placeholder).
 */
export function formatDocLine(doc: {
  type: string | undefined;
  path: string;
  summary: string;
  status: string | undefined;
}): string {
  const typeSegment = doc.type !== undefined ? `[${doc.type}] ` : "";
  const statusSegment = doc.status !== undefined ? ` (${doc.status})` : "";
  return `- ${typeSegment}${doc.path} — ${doc.summary}${statusSegment}`;
}

/** Default ordering: alphabetical by `path` (the zero-config/loose default). */
function compararAlfabetico(a: IndexEntry, b: IndexEntry): number {
  return a.path.localeCompare(b.path);
}

/**
 * Renders INDEX.md: one line per document. Ordering is delegated to an
 * injectable comparator (default = alphabetical by `path`); pass the
 * `strict` declared-taxonomy comparator from `createIndexComparator` to
 * order by the declared `types` sequence instead.
 */
export function renderIndexMd(
  docs: IndexEntry[],
  compare: (a: IndexEntry, b: IndexEntry) => number = compararAlfabetico,
): string {
  const lines = [...docs].sort(compare).map((doc) =>
    formatDocLine({
      type: doc.type,
      path: doc.path,
      summary: displaySummary(doc),
      status: doc.status,
    }),
  );
  const header = `${INDEX_TITLE}\n\n${GENERATED_NOTICE}\n`;
  return lines.length === 0 ? header : `${header}\n${lines.join("\n")}\n`;
}
